import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import AuthButton from '@/components/ui/AuthButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="absolute right-2 top-2 z-50">
          <AuthButton />
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
